const jokes = [
  'How did the programmer die in the shower? He read the shampoo bottle instructions: Lather. Rinse. Repeat.',
  "How many programmers does it take to change a light bulb? None - It's a hardware problem",
  'Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.',
  "There are only 10 kinds of people in this world: those who know binary and those who don't.",
  '"Knock, knock." "Who\'s there?" very long pause… "Java."',
  'Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.',
  'The generation of random numbers is too important to be left to chance.',
  'The computer is mightier than the pen, the sword, and usually, the programmer.',
  'Debugging: Removing the needles from the haystack.',
  'Programmer (noun): A machine that turns coffee into code.',
  'Algorithm (noun): Word used by programmers when they do not want to explain what they did.',
  'A SQL query goes into a bar, walks up to two tables and asks, "Can I join you?"',
  'Why are Assembly programmers always soaking wet? They work below C-level.',
  "How do you tell HTML from HTML5? Try it out in Internet Explorer. Did it work? No? It's HTML5.",
  "3 SQL databases walked into a NoSQL bar. A little while later they walked out, because they couldn't find a table.",
  '["hip", "hip"]',
  '; - Hide and seek champion since 1994',
  "What's the object-oriented way to become wealthy? Inheritance.",
  'To understand what recursion is, you must first understand recursion.',
  'ASCII dumb question, get a dumb ANSI.',
  "Why did the programmer quit his job? Because he didn't get arrays.",
  "UNIX is user friendly. It's just very particular about who its friends are.",
  'There are 2 hard problems in computer science: caching, naming, and off-by-1 errors.',
  '"Knock knock." "Race condition." "Who\'s there?"',
  'Chuck Norris can take a screenshot of his blue screen of death',
  'Chuck Norris writes code that optimizes itself.',
  'All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.',
  'Chuck Norris can write infinite recursion functions…and have them return.',
  "Chuck Norris doesn't use web standards as the web will conform to him.",
  'Chuck Norris can delete the Recycling Bin.',
  'Chuck Norris can unit test entire applications with a single assert.',
  'Software can be fast, reliable and cheap. Choose any two.',
];

export default jokes;
